packages:
  - packages/*

onlyBuiltDependencies:
  - '@mastra/core'
  - '@prisma/client'
  - '@prisma/engines'
  - canvas
  - esbuild
  - onnxruntime-node
  - prisma
  - protobufjs
  - sharp
  - tree-sitter
